import uuid
from datetime import datetime, timezone
from typing import Dict, Any, Optional
from sqlalchemy.orm import Session
from backend.app.services.investigation_service import get_entity_dossier
from backend.app.schemas.report import ReportResponse, ReportGenerateRequest
from backend.app.services.audit_service import log_audit_event

DISCLAIMER_TEXT = (
    "DISCLAIMER & LEGAL NOTICE: This report is generated by TraceX as an investigative lead brief based on statistical "
    "anomaly detection and graph heuristics from the provided dataset metadata. This document does NOT constitute proof of "
    "criminal activity, guilt, illicit intent, or definitive wallet ownership. Observed IP associations represent network-layer "
    "p2p propagation evidence only. All findings must be independently validated by forensic investigators."
)

def generate_investigation_report(
    db: Session,
    request: ReportGenerateRequest,
    user_name: str = "investigator"
) -> ReportResponse:
    dossier = get_entity_dossier(db, request.entity_id)
    report_id = f"TRACEX-REP-{uuid.uuid4().hex[:8].upper()}"
    now = datetime.now(timezone.utc)

    # Build Markdown Content
    md_lines = [
        f"# {request.title}",
        f"**Report ID**: `{report_id}`  ",
        f"**Target Entity**: `{request.entity_id}` ({dossier.entity_type})  ",
        f"**Generated**: {now.strftime('%Y-%m-%d %H:%M:%S UTC')} by `{user_name}`  ",
        f"**Risk Priority**: `{dossier.risk_score}/100` ({dossier.severity}) | **ML Anomaly Score**: `{dossier.anomaly_score:.2f}`  ",
        "",
        "> [!IMPORTANT]",
        f"> {DISCLAIMER_TEXT}",
        "",
        "## 1. Executive Summary",
        f"Entity `{request.entity_id}` has been classified with a priority score of **{dossier.risk_score}/100** ({dossier.severity} Severity) based on multivariate Isolation Forest anomaly detection and graph behavioral signals.",
        f"- **Total Volume**: {dossier.total_volume_btc:.4f} BTC across {dossier.transaction_count} transactions.",
        f"- **Counterparties**: {dossier.unique_counterparties} unique sending/receiving addresses.",
        f"- **Jurisdictions**: Observed across {len(dossier.observed_countries)} countries and {len(dossier.observed_asns)} ASNs.",
        "",
        "## 2. Mathematical Explainability & Key Indicators",
        "The alert priority is derived from the following statistical deviations against the baseline population:"
    ]

    for r in dossier.explanation_reasons:
        md_lines.append(f"- {r}")

    if dossier.features:
        md_lines.extend([
            "",
            "### Feature Space Breakdown",
            "| Feature | Observed Value | Population Baseline (Median) | z-Score |",
            "| :--- | :--- | :--- | :--- |"
        ])
        for f_name, f_val in list(dossier.features.items())[:8]:
            dev = dossier.feature_deviations.get(f_name, {})
            b_med = dev.get("baseline_median", "N/A")
            z = dev.get("z_score", "N/A")
            md_lines.append(f"| `{f_name}` | {f_val} | {b_med} | {z} |")

    if request.include_evidence:
        md_lines.extend([
            "",
            "## 3. Associated Transactions & Network Evidence",
            "| TXID | Total Volume (BTC) | Fee (BTC) | Timestamp |",
            "| :--- | :--- | :--- | :--- |"
        ])
        for tx in dossier.recent_transactions[:10]:
            txid = tx.get("txid", "N/A")
            vol = tx.get("input_total", 0.0)
            fee = tx.get("fee", 0.0)
            ts = tx.get("timestamp", "N/A")
            md_lines.append(f"| `{txid[:16]}...` | {vol:.4f} | {fee:.4f} | {ts} |")

        if dossier.observed_ips:
            md_lines.extend([
                "",
                "### Network Observation Layer",
                "*(Note: Network relay records indicate broadcast observations, NOT verified identity proof)*",
                "| Relay IP | Country | Autonomous System (ASN) | Observation Time |",
                "| :--- | :--- | :--- | :--- |"
            ])
            for ip_info in dossier.observed_ips[:10]:
                md_lines.append(f"| `{ip_info.get('ip')}` | {ip_info.get('country')} | {ip_info.get('asn')} | {ip_info.get('timestamp', 'N/A')} |")

    if request.analyst_notes:
        md_lines.extend([
            "",
            "## 4. Investigator Notes & Observations",
            request.analyst_notes
        ])

    md_lines.extend([
        "",
        "---",
        "*Report compiled automatically by TraceX Forensic Intelligence Engine v1.0.0 (Offline Mode)*"
    ])

    markdown_str = "\n".join(md_lines)

    log_audit_event(
        db=db,
        action="INVESTIGATION_REPORT_GENERATED",
        target_type="REPORT",
        target_id=report_id,
        details={"entity_id": request.entity_id, "title": request.title},
        user_name=user_name
    )

    return ReportResponse(
        report_id=report_id,
        generated_at=now,
        title=request.title,
        entity_id=request.entity_id,
        entity_type=dossier.entity_type,
        risk_score=dossier.risk_score,
        anomaly_score=dossier.anomaly_score,
        severity=dossier.severity,
        disclaimer=DISCLAIMER_TEXT,
        explanation=dossier.explanation_reasons,
        feature_breakdown=dossier.features,
        transaction_evidence=dossier.recent_transactions,
        network_observations=dossier.observed_ips,
        counterparties=[],
        analyst_notes=request.analyst_notes,
        markdown_content=markdown_str
    )
